on:
  workflow_call:

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # - name: Publish to PyPI using trusted publishing
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     attestations: false

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: false
          # verbose: true
          # password: ${{ secrets.TESTPYPI_API_TOKEN }}
